#!/bin/bash
echo "🚨 IMPORTANT: Local .mcp.json was removed from Claude_MCPServer_Dev1!"
echo "✅ Now using DEV1-SPECIFIC global config: ~/.claude/claude_code_config_dev1.json"
echo ""
echo "To restart Claude Code with DEV1 MCP servers:"
echo "1. Exit this Claude Code session (Ctrl+C or quit)"
echo "2. Run: claude --mcp-config ~/.claude/claude_code_config_dev1.json"
echo ""
echo "This will load DEV1 MCP servers that point to Claude_MCPServer_Dev1 files."
echo "You can run BOTH projects simultaneously since they use STDIO (no port conflicts)."
echo ""
echo "DEV1 MCP config servers:"
cat ~/.claude/claude_code_config_dev1.json | jq -r '.mcpServers | keys[]' 2>/dev/null || echo "Install jq for formatted output"
echo ""
echo "Main project uses: claude --mcp-config ~/.claude/claude_code_config.json"
echo "Dev1 project uses: claude --mcp-config ~/.claude/claude_code_config_dev1.json"